# Generated by Django 3.0.6 on 2020-05-16 04:48

from django.db import migrations


def create_data(apps, schema_editor):
    Student = apps.get_model('cresch', 'Student')
    Student(name="Ameen", grade="Third grade"
            ,school = "Gowtham Model Schools"
            ,email="ameenkhan13.p@gmail.com", userid="18BNC00575", phone="9705820585").save()


class Migration(migrations.Migration):

    dependencies = [
        ('cresch', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_data),
    ]
